# This file is part of smartoptim.
# https://github.com/thumby/smartoptim

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Thumby <dev@thumby.io>

language: python

python:
    - "2.7"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
